export const FUNDING_DETAIL_LABELS = ['FRR', 'BID', 'BID PERIOD', 'BID SIZE', 'ASK', 'ASK PERIOD', 'ASK SIZE', 'DAILY CHANGE', 'DAILY CHANGE PERC', 'LAST PRICE', 'VOLUME', 'HIGH', 'LOW', null, null, 'FRR AMOUNT AVAILABL']
export const TRADING_DETAIL_LABELS = ['BID', 'BID SIZE', 'ASK', 'ASK SIZE', 'DAILY CHANGE', 'DAILY CHANGE RELATIVE', 'LAST PRICE', 'VOLUME', 'HIGH', 'LOW']
